### ISSUE TITLE
Issue in Sparsify?

### ISSUE THREAD

**Issue by bpotard** [mozilla/LPCNet#10]
In lpcnet.py, the following line do not seem to have the intended effect:

```python
if self.batch < self.t_start or ((self.batch-self.t_start) % self.interval != 0 and self.batch < self.t_end):
            #print("don't constrain");
            pass
```

I assume the intention is to run the "sparsification" every `self.interval` from `self.t_start` to `self.t_end`. However, what it actually does is, in addition to this, run it for **every single batch** after `self.t_end`.

So I suggest the following correction:
```python
if self.batch < self.t_start or ((self.batch-self.t_start) % self.interval != 0) or self.batch >= self.t_end:
            #print("don't constrain");
            pass
```

**Comment by jmvalin** [comment]
That behaviour is intended. Once the model has reached the desired sparseness, then it needs to remain that way.
