### ISSUE TITLE
time delay issue of synthesized wav

### ISSUE THREAD

**Issue by jarred1989** [mozilla/LPCNet#101]
Did someone notice the issue, the lpcnet synthesized wav is about 30ms time delay compared with original wav?

Below is original wav
![orig](https://user-images.githubusercontent.com/19771216/74723537-b801d300-5275-11ea-85d1-1f89bc9c6534.JPG)

Below is synthesized wav
![gen](https://user-images.githubusercontent.com/19771216/74723744-09aa5d80-5276-11ea-8666-d56c58b544c9.JPG)

it would cause some problem when I trim tail silence of training data. How to deal with it?

**Comment by jmvalin** [comment]
The exact delay is 25 ms, of which 20 ms is from the 2-frame look-ahead in the features, and 5 ms is for the windowing. You'll need to compensate for that.
