### ISSUE TITLE
when run  test_lpcnet.py ,i met a bug [int too large to convert to C long]

### ISSUE THREAD

**Issue by Mao-JianGuo** [mozilla/LPCNet#104]
after synthesize *.f32 with tacotron2 
and i run test_lpcnet.py , a bug occured

Traceback (most recent call last):
  File "C:/PyCharmProject/tacotronChinese/LPCTron/LPCNet/src/test_lpcnet.py", line 104, in <module>
    np.array([np.round(mem)], dtype='int16').tofile(fout)
OverflowError: Python int too large to convert to C long

anybody can help me ,i don't know how to solve it

**Comment by iGuaZi** [comment]
I met the same problem. Could you share the solution?

**Comment by iGuaZi** [comment]
@Mao-JianGuo

**Comment by KamijouMikoto** [comment]
Hi, I faced this problem, too.
I wonder how you solved it. Could you please give some advice and experience here?
