### ISSUE TITLE
Training 24K model is meeting bad sound quality

### ISSUE THREAD

**Issue by yangxipeng** [mozilla/LPCNet#110]
I'd like to train a model using 24kHz data instead of 16kHz data. but sound has bad  quality. can you tell me how to change parameter .

**Comment by xiaoyangnihao** [comment]
> I'd like to train a model using 24kHz data instead of 16kHz data. but sound has bad quality. can you tell me how to change parameter .

Do you achieve success ? can you share the parameter setting?
