### ISSUE TITLE
How to caculate LPC by MFCC or mel spectrogram

### ISSUE THREAD

**Issue by cyxomo** [mozilla/LPCNet#117]
the LPC and BFCC could caculated by dump_data.c, however , how to caculate LPC by MFCC or mel spectrogram. Especially, how to get 'eband5ms' and 'compensation' of 80-dim mel ?

**Comment by zhangjh915** [comment]
I think the LPC and BFCC are extracted and calculated from the wavs instead of mel spectrograms. You need to have a model to predict LPC instead of mel spectrogram for TTS.

**Comment by cyxomo** [comment]
> 
> 
> I think the LPC and BFCC are extracted and calculated from the wavs instead of mel spectrograms. You need to have a model to predict LPC instead of mel spectrogram for TTS.

In LPCNet, LPC is caculated by BFCC. I want to use mel spectrogram as input for LPCNet, but, I do not know how to caculate LPC by mel spectrogram. And in code of LPCNet the 'eband5ms' and 'compensation' is hard written as 
static const opus_int16 eband5ms[] = {
/*0  200 400 600 800  1k 1.2 1.4 1.6  2k 2.4 2.8 3.2  4k 4.8 5.6 6.8  8k*/
    0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 14, 16, 20, 24, 28, 34, 40
};

static const float compensation[] = {
    0.8f, 1.f, 1.f, 1.f, 1.f, 1.f, 1.f, 1.f, 0.666667f, 0.5f, 0.5f, 0.5f, 0.333333f, 0.25f, 0.25f, 0.2f, 0.166667f,
    0.173913f
};
they are used to get LPC from BFCC ,so how to get mel corresponding value?

**Comment by yingfenging** [comment]
> I think the LPC and BFCC are extracted and calculated from the wavs instead of mel spectrograms. You need to have a model to predict LPC instead of mel spectrogram for TTS.

Do you know what model can predict LPC? Thank you！

**Comment by zhangjh915** [comment]
> > I think the LPC and BFCC are extracted and calculated from the wavs instead of mel spectrograms. You need to have a model to predict LPC instead of mel spectrogram for TTS.
> 
> Do you know what model can predict LPC? Thank you！

For example, use Tacotron to predict lpc instead of mel.

**Comment by yingfenging** [comment]
> > > I think the LPC and BFCC are extracted and calculated from the wavs instead of mel spectrograms. You need to have a model to predict LPC instead of mel spectrogram for TTS.
> > 
> > 
> > Do you know what model can predict LPC? Thank you！
> 
> For example, use Tacotron to predict lpc instead of mel.

Hello, I don't quite understand. In the original code, the input of LPCnet is BFCC, and the LPC coefficients used in prediction are obtained from BFCC.
Do you mean using TACTRON to predict BFCC and LPC coefficients? In other words, the LPC coefficients used in the prediction are also predicted by TACTRON, not calculated from BFCC? Thank you. @zhangjh915

**Comment by zhangjh915** [comment]
> > > > I think the LPC and BFCC are extracted and calculated from the wavs instead of mel spectrograms. You need to have a model to predict LPC instead of mel spectrogram for TTS.
> > > 
> > > 
> > > Do you know what model can predict LPC? Thank you！
> > 
> > 
> > For example, use Tacotron to predict lpc instead of mel.
> 
> Hello, I don't quite understand. In the original code, the input of LPCnet is BFCC, and the LPC coefficients used in prediction are obtained from BFCC.
> Do you mean using TACTRON to predict BFCC and LPC coefficients? In other words, the LPC coefficients used in the prediction are also predicted by TACTRON, not calculated from BFCC? Thank you. @zhangjh915

Sorry I misunderstood your question. Basically you can use Tacotron to predict the 20-dim features including BFCC and pitch. Then use BFCC to calculate LPC coefficients and LPC gain to align the inputs of LPCNet.

There are related issues about this. Check them out! #52 #93 I did not try the solutions in those issues though. I have my own implementations but the ideas would be the same.

**Comment by zhangjh915** [comment]
> > I think the LPC and BFCC are extracted and calculated from the wavs instead of mel spectrograms. You need to have a model to predict LPC instead of mel spectrogram for TTS.
> 
> In LPCNet, LPC is caculated by BFCC. I want to use mel spectrogram as input for LPCNet, but, I do not know how to caculate LPC by mel spectrogram. And in code of LPCNet the 'eband5ms' and 'compensation' is hard written as
> static const opus_int16 eband5ms[] = {
> /_0 200 400 600 800 1k 1.2 1.4 1.6 2k 2.4 2.8 3.2 4k 4.8 5.6 6.8 8k_/
> 0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 14, 16, 20, 24, 28, 34, 40
> };
> 
> static const float compensation[] = {
> 0.8f, 1.f, 1.f, 1.f, 1.f, 1.f, 1.f, 1.f, 0.666667f, 0.5f, 0.5f, 0.5f, 0.333333f, 0.25f, 0.25f, 0.2f, 0.166667f,
> 0.173913f
> };
> they are used to get LPC from BFCC ,so how to get mel corresponding value?

Sorry I mixed up LPC and BFCC in my last reply. I mean you need a model to predict the 20-dim features including BFCC and pitch parameters, and then use BFCC to calculate LPC. I am not sure if you can calculate LPC directly from mel spectrogram. The authors haven't appear for a while lol. Please tell me if you find the solution. :)

**Comment by yingfenging** [comment]
@zhangjh915   Ok. Thank you. Do you use LPCnet to synthesize singing voices? How's the effect?
