### ISSUE TITLE
https://jmvalin.ca/misc_stuff/lpcnet_models/ broken

### ISSUE THREAD

**Issue by jcacerec** [mozilla/LPCNet#119]
The link with the model https://jmvalin.ca/misc_stuff/lpcnet_models/ is broken, where can we find it?

**Comment by montronic247** [comment]
This query seems to have appeared in different forms three times in the past 30 days.  If it is possible to resolve I would also be really appreciative.

**Comment by jmvalin** [comment]
The models are back after some server problems. Sorry for the inconvenience.
