### ISSUE TITLE
How to finetune on the sparse LPCNet model?

### ISSUE THREAD

**Issue by zhangjh915** [mozilla/LPCNet#127]
I have trained a LPCNet model with thousands of speakers and want to finetune a new speaker with limited data. What is the best way to finetune on the limited data? Below are what I have tried:
1. Train a sparse LPCNet multi-speaker model and finetune on the new data with unchanged sparsity
2. Train a sparse LPCNet multi-speaker model and finetune on the new data with sparsity applying from the start, i.e. 0% -> 80%
3. Train a dense LPCNet multi-speaker model and finetune on the new data with sparsity applied

But none of them generate better samples than training the limited data from scratch. I find it very strange since in most cases, finetuning on an average model improves the performance of models with limited data, and I suspect it is related to the sparsity. In General, what is the best way to finetune models with sparsity?

**Comment by justforhome** [comment]
your dataset in Chinese or English ?
