### ISSUE TITLE
when train lpcnet, cannot import name 'CuDNNGRU'

### ISSUE THREAD

**Issue by xajdlg** [mozilla/LPCNet#140]
so，which version  of keras and tensorflow ? Now, my version: keras ==2.4.3 tensorflow == 2.2.1

**Comment by jmvalin** [comment]
There's tensorflow 2 training code in the training_tf2/ directory

**Comment by xajdlg** [comment]
thanks you

**Comment by xajdlg** [comment]
> There's tensorflow 2 training code in the training_tf2/ directory

thank you
