### ISSUE TITLE
Is exp_improved_simd2 branch ready for production?

### ISSUE THREAD

**Issue by rafael2k** [mozilla/LPCNet#151]
Hi Jean-Marc,

Can we consider exp_improved_simd2 branch ready for production?

**Comment by jmvalin** [comment]
Well, that's the question I'd like to ask you :-) It seems to be working better -- and 2x faster -- for me, but it received only limited testing. So more testing would be welcome.

**Comment by rafael2k** [comment]
Right. Indeed, it is working better and faster. Thanks Jean-Marc! I'll put it in production, and any problem we have, I create a ticket here. Btw, LPCNet is the free software state-of-the-art vocoder by far. Lyra is a joke... "open source" mixed with binary stuff to link to, training pipeline also closed source... really awful.
