### ISSUE TITLE
Landed optimizations to master

### ISSUE THREAD

**Issue by jmvalin** [mozilla/LPCNet#154]
I just landed all the optimizations from the exp_improved_simd2 branch to master. The improvements should make LPCNet about 2x faster than it was on x86. Trained models are similar, but not quite compatible, so any custom model will need to be retrained. However, the autogen.sh script will still download a compatible, up-to-date model. The main reason for the speedup is the use of 8-bit weights. If you suspect those are affecting quality, you can use float weights by adding --disable-dot-product to the configure script. I'd be curious to hear of any feedback on the newer model.

**Comment by rafael2k** [comment]
Thanks Jean-Mark. I'll carry some tests with the updated master.
