### ISSUE TITLE
What does fixed numbers mean ?

### ISSUE THREAD

**Issue by xiaoyangnihao** [mozilla/LPCNet#161]
@jmvalin In the function: lpc_from_bands() in line 226 in script freq.c, there are three fixed numbers 320/12/38., can you tell me what each of them means?
```
   /* -40 dB noise floor. */
   ac[0] += ac[0]*1e-4 + 320/12/38.;
```

**Comment by YangWangGit** [comment]
@xiaoyangnihao  I have exactly the same question. Any idea or hypothesis is welcome! Thanks.
