### ISSUE TITLE
How to generate .s16 files from wav files?

### ISSUE THREAD

**Issue by Hongjiang-Yu** [mozilla/LPCNet#176]
I am going to train a model using my own dataset. The speech files in the dataset are wav files, while the input format for LPCNet is .s16. I am not familiar with the s16 format. Could you please tell me how to batchly change the wav files to s16 files ？

**Comment by sundekai** [comment]
@Hongjiang-Yu  src/concat.sh

**Comment by Hongjiang-Yu** [comment]
> src/concat.sh

Thank you！ It works
