### ISSUE TITLE
No concat.sh

### ISSUE THREAD

**Issue by changeforan** [mozilla/LPCNet#2]
Hi,

I note that there is no concat.sh in the src folder, so how can I generate the input file?

Thank you.

**Comment by bpotard** [comment]
I used the following command:
```
find . -iname \*.wav -printf "%p " | xargs -d " " -I{} sox {} -t raw - > ../input.s16
```
I am not sure it does *exactly* the same as the concat.sh command, but the models have trained fine.

**Comment by changeforan** [comment]
@bpotard Thank you for your reply.
