### ISSUE TITLE
how about to use 12.5ms for one frame instead of 10ms?

### ISSUE THREAD

**Issue by yxlijinzhu** [mozilla/LPCNet#20]
Can I modify the codes to train the lpcnet vocoder using frame size 12.5ms? Will it be as good as 10ms?

**Comment by softrime** [comment]
@yxlijinzhu have you tried change different frame size? how do you modify the feature extract scripts? I tried using 5ms frame size but got 'nan' in the first frame.

**Comment by wangshiyao-1119** [comment]
> Can I modify the codes to train the lpcnet vocoder using frame size 12.5ms? Will it be as good as 10ms?

Hello, I am currently changing the frame length to 12.5. May I ask you:
#define FRAME_SIZE_5MS (2) 
#define OVERLAP_SIZE_5MS (2)   
#define TRAINING_OFFSET_5MS (1)   
#define WINDOW_SIZE_5MS (FRAME_SIZE_5MS + OVERLAP_SIZE_5MS)

How did you change these parameters? 
（I doubled each of these parameters to train properly）

**Comment by wangshiyao-1119** [comment]
> @yxlijinzhu have you tried change different frame size? how do you modify the feature extract scripts? I tried using 5ms frame size but got 'nan' in the first frame.

Hello, I also encountered this situation, have you solved it?

**Comment by yxlijinzhu** [comment]
I haven't done this change.-------- 原始邮件 --------发件人： wangshiyao-1119 ***@***.***>日期： 2021年6月29日周二 傍晚5:02收件人： mozilla/LPCNet ***@***.***>抄送： yxlijinzhu ***@***.***>, Mention ***@***.***>主    题： Re: [mozilla/LPCNet] how about to use 12.5ms for one frame instead of 10ms? (#20)

@yxlijinzhu have you tried change different frame size? how do you modify the feature extract scripts? I tried using 5ms frame size but got 'nan' in the first frame.

Hello, I also encountered this situation, have you solved it?
