### ISSUE TITLE
magic number 320/12/38. 

### ISSUE THREAD

**Issue by opencvbaby** [mozilla/LPCNet#35]
/* -40 dB noise floor. */
ac[0] += ac[0]*1e-4 + 320/12/38.;

why add 320/12/38. ? 
What number should be for 44.1KHz ?   

Thank you very much ~

**Comment by opencvbaby** [comment]
it's trivial

**Comment by xiaoyangnihao** [comment]
@opencvbaby hi, can you explain something about these magin number if I want to change the sample rate?
