### ISSUE TITLE
About loss curve

### ISSUE THREAD

**Issue by hdmjdp** [mozilla/LPCNet#37]
![image](https://user-images.githubusercontent.com/26831425/54338829-f78b6c80-466d-11e9-9dbd-e9af11e62722.png)
why there exists oscillating part?

**Comment by mikesun4096** [comment]
> ![image](https://user-images.githubusercontent.com/26831425/54338829-f78b6c80-466d-11e9-9dbd-e9af11e62722.png)
> why there exists oscillating part?

Is this curve generated by the code without changing one line?

**Comment by zhengao1993** [comment]
I am training on another dataset. The loss was about 3.1 after the first epoch, but not decreasing much after the 4th or 5th epoch (around 2.99). Considering that one epoch is about 300k steps, I believe your training graph is correct.
