### ISSUE TITLE
Some question about tensorfow version？

### ISSUE THREAD

**Issue by yanggeng1995** [mozilla/LPCNet#43]

**Comment by yanggeng1995** [comment]
Hello, I tried several versions of tensorflow and found the same error.
![55273301-4ee33b00-5304-11e9-8f3e-63769f13ebfc](https://user-images.githubusercontent.com/16759406/55283771-bb117d80-539c-11e9-87ec-76fe0d9f8e3b.JPG)

**Comment by xiaoqiang-ok** [comment]
(tfgpu) [huangqq@server121 LPCNet]$ python ./src/dump_lpcnet.py lpcnet24g_384_10_G16_01.h5 
Using TensorFlow backend.
  return f(*args, **kwds)
Traceback (most recent call last):
  File "./src/dump_lpcnet.py", line 212, in <module>
    model, _, _ = lpcnet.new_lpcnet_model(rnn_units1=384, use_gpu=False)
  File "/hzqpath/temp/LPCNet/src/lpcnet.py", line 152, in new_lpcnet_model
    gru_out1, _ = rnn(rnn_in)
  File "/hzqpath/software/anaconda3/envs/tfgpu/lib/python3.6/site-packages/keras/layers/recurrent.py", line 532, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/hzqpath/software/anaconda3/envs/tfgpu/lib/python3.6/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/hzqpath/software/anaconda3/envs/tfgpu/lib/python3.6/site-packages/keras/layers/recurrent.py", line 1649, in call
    initial_state=initial_state)
  File "/hzqpath/software/anaconda3/envs/tfgpu/lib/python3.6/site-packages/keras/layers/recurrent.py", line 649, in call
    input_length=timesteps)
  File "/hzqpath/software/anaconda3/envs/tfgpu/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 3011, in rnn
    maximum_iterations=input_length)
TypeError: while_loop() got an unexpected keyword argument 'maximum_iterations'

**Comment by xiaoqiang-ok** [comment]
> (tfgpu) [huangqq@server121 LPCNet]$ python ./src/dump_lpcnet.py lpcnet24g_384_10_G16_01.h5
> Using TensorFlow backend.
> return f(*args, **kwds)
> Traceback (most recent call last):
> File "./src/dump_lpcnet.py", line 212, in 
> model, _, _ = lpcnet.new_lpcnet_model(rnn_units1=384, use_gpu=False)
> File "/hzqpath/temp/LPCNet/src/lpcnet.py", line 152, in new_lpcnet_model
> gru_out1, _ = rnn(rnn_in)
> File "/hzqpath/software/anaconda3/envs/tfgpu/lib/python3.6/site-packages/keras/layers/recurrent.py", line 532, in **call**
> return super(RNN, self).**call**(inputs, **kwargs)
> File "/hzqpath/software/anaconda3/envs/tfgpu/lib/python3.6/site-packages/keras/engine/base_layer.py", line 457, in **call**
> output = self.call(inputs, **kwargs)
> File "/hzqpath/software/anaconda3/envs/tfgpu/lib/python3.6/site-packages/keras/layers/recurrent.py", line 1649, in call
> initial_state=initial_state)
> File "/hzqpath/software/anaconda3/envs/tfgpu/lib/python3.6/site-packages/keras/layers/recurrent.py", line 649, in call
> input_length=timesteps)
> File "/hzqpath/software/anaconda3/envs/tfgpu/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 3011, in rnn
> maximum_iterations=input_length)
> TypeError: while_loop() got an unexpected keyword argument 'maximum_iterations'

my tensorflow version is  1.4  （gpu）

**Comment by yanggeng1995** [comment]
my environment is tensorflow-gpu==1.12.0 and Keras== 2.2.4

**Comment by xiaoqiang-ok** [comment]
> my environment is tensorflow-gpu==1.12.0 and Keras== 2.2.4

is your environment ok？

**Comment by yanggeng1995** [comment]
yes, you can try it.

**Comment by xiaoqiang-ok** [comment]
> my environment is tensorflow-gpu==1.12.0 and Keras== 2.2.4
I created an anaconda environment whith python3.6  tensorflow==1.12.0 and Keras==2.2.4
then I run this python ./src/**dump_lpcnet.py** lpcnet24g_384_10_G16_01.h5
it works
thank U！
