### ISSUE TITLE
Illegal Instruction with "lpcnet_demo"

### ISSUE THREAD

**Issue by ahmed-fau** [mozilla/LPCNet#46]
Hi,

Thanks for this nice work. I am new to use LPCNet and currently try to use "lpcnet_demo". Unfortunately, running it always gives me the following error message:

> Illegal Instruction 

Is there any clarification for possible reasons why I am getting such an error message? I have successfully built the project on my Linux machine and used "ffmpeg" command to convert from wav to PCM-16bits.

Regards

**Comment by J-Fo-S** [comment]
@ahmed-fau I am experiencing the same error when trying to run the demo on a macbook - can you provide the solution (assuming you found it)? Thank you

**Comment by J-Fo-S** [comment]
in my setup (mac with conda environment), the issue is possibly resolvable here: https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html

But I have not yet tried as I'll just use LPCNet on linux for now
