### ISSUE TITLE
train a model using 24kHz

### ISSUE THREAD

**Issue by luvpine** [mozilla/LPCNet#5]
Your paper is very impressive. 🙂
I'd like to train a model using 24kHz data instead of 16kHz data.
Is it easily possible?

**Comment by jmvalin** [comment]
The correct way to do it involves adding a few bands and changing a few constants throughout the code. It's not fundamentally hard, but easy to forget a few things. That being said, considering that 24 isn't that big a change compared to 16, you may be able to get away with pretending that your 24 kHz audio is really 16 kHz and not modifying the code at all.

**Comment by hdmjdp** [comment]
@luvpine have you got good wav using 24k without modifying code?

**Comment by luvpine** [comment]
@hdmjdp No, I mean I'd like to make 24kHz wav file (high quality), not train using 24kHz data.

**Comment by hdmjdp** [comment]
i know. do you suceeed got the 24khz wav？




| |
胡大盟
|
|
邮箱：hdmjdp@163.com
|

签名由 网易邮箱大师 定制

On 01/04/2019 15:51, RIM SUNMI wrote:

@hdmjdp No, I mean I'd like to make 24kHz wav file (high quality), not train using 24kHz data.

**Comment by hdmjdp** [comment]
I know, do you modify frame_size=160？

**Comment by hdmjdp** [comment]
I know, do you modify frame_size=160？

**Comment by belevtsoff** [comment]
@jmvalin Thanks a lot for the info! It would be great if you could give more details on what to change to switch to 22050Hz. Specifically, I was thinking of changing these things:

* increase NB_BANDS=24.
* change FRAME_SIZE to 256 (~11.6ms)
* OVERLAP_SIZE=256
* TRAINIG_OFFSET=128
* WINDOW_SIZE=512

I'm not sure about the pitch parameters though. In particular, currently:
PITCH_MIN_PERIOD 32
PITCH_MAX_PERIOD 256
PITCH_FRAME_SIZE 320

My guess is that the first two should be increased to match the difference in sampling rates, but should they be power of two? Also I guess the last parameter should be increased to match the window length. Do these changes sound right to you? Thanks a lot!

**Comment by luvpine** [comment]
@hdmjdp @belevtsoff  In my case, change 16kHz -> 24kHz.

Key changing things:
* increase NB_BANDS=20
* change FRAME_SIZE = 480
* change total features 55 -> 59.

Also I  changed nb_features , nb_total_features, sampling rate, feature index num(because features is increased), Conv1D layer filters size.

**Comment by belevtsoff** [comment]
@luvpine thanks! This set up sort of works, but I'm experiencing lowering of the pitch. Have you observed anything like this?

**Comment by belevtsoff** [comment]
UPD: actually it keeps producing really bad results for me with 24kHz, can't figure out what's the problem

**Comment by opencvbaby** [comment]
I tried 44.1KHz and 48KHz,  also produced bad waveform,  train and validation loss are all right, don't know why

**Comment by opencvbaby** [comment]
solved the problem, now 44.1KHz works well

**Comment by belevtsoff** [comment]
@opencvbaby Great! Can you share the full recipe?

**Comment by opencvbaby** [comment]
@belevtsoff Sorry, I can't share the recipe.   There are some noise in high frequency,  I am still optimizing it.   Maybe you should  take care of  pitch_embedding part

**Comment by tsungruihon** [comment]
@luvpine could you share the parameter you have changed like nb_features , nb_total_features, sampling rate, feature index num and Conv1D layer filters size ?

**Comment by linzai1992** [comment]
@belevtsoff Have you figure out your problems?  Could you give some advice?

**Comment by xiaoyangnihao** [comment]
> pitch_embedding

@opencvbaby hi, what do you mean by taking care of pitch_embedding part? can you make some explainations?
