### ISSUE TITLE
The following error occurred when I build the code

### ISSUE THREAD

**Issue by szm19931109** [mozilla/LPCNet#51]
![image](https://user-images.githubusercontent.com/37999223/56402541-42f9f180-6290-11e9-9b53-ea064509f47a.png)

**Comment by szm19931109** [comment]
src/vec.h:141:27: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'y'
          float * restrict y;
                           ^
src/vec.h:141:27: error: 'y' undeclared (first use in this function)
src/vec.h:142:10: warning: ISO C90 forbids mixed declarations and code [-Wpedantic]
          float xj;

**Comment by candlewill** [comment]
The simplest method to solve this problem is to remove `restrict` , or you can switch your compiler to c99.

**Comment by xiaoqiang-ok** [comment]
on linux of centos 7.2， try compile like this：
export CFLAGS='-O3 -g -mavx2 -mfma **-std=c99**'
./configure
make

**Comment by xiaoqiang-ok** [comment]
https://github.com/mozilla/LPCNet/issues/47

**Comment by wangshiyao-1119** [comment]
> on linux of centos 7.2， try compile like this：
> export CFLAGS='-O3 -g -mavx2 -mfma **-std=c99**'
> ./configure
> make

Thank you for your answer, the problem that has troubled me for several days has been solved!
