### ISSUE TITLE
Transfer the model to pytorch

### ISSUE THREAD

**Issue by attitudechunfeng** [mozilla/LPCNet#54]
I'm trying to transfer this project to pytorch, and i'd like to know what should i change if i want to reuse the c files. Do i only need to change the pytorch model into the keras-like model? @jmvalin  I'm now met troubles with the c program when running the sparse gru layer, the results differ from the pytorch model.

**Comment by keishatsai** [comment]
@attitudechunfeng Hi ,
Have you managed to transfer the model to pytorch?

**Comment by SuperEver** [comment]
I have successfully done it.  keras , pytorch  and their c model will get nearly the same result.

**Comment by sundekai** [comment]
@SuperEver  您好 请问能否开源你的pytorch复现呢

**Comment by attitudechunfeng** [comment]
邮件已收~谢谢 by 王春峰
