### ISSUE TITLE
What is the future for this project?

### ISSUE THREAD

**Issue by nmstoker** [mozilla/LPCNet#67]
This looks like a really interesting project, but I see that @jmvalin has recently left Mozilla for AWS and there haven't been responses to issues from the contributors since February (I think)

Is it on-hold permanently?

**Comment by zenny** [comment]
+1 to @nmstoker 

@nmstoker btw I saw your useful implementation of ASR and TTS (https://www.youtube.com/watch?v=cDU6Oz1bNoY). Would you mind sharing how you accomplished and the pointers to your voice dataset (really sound awesome)?  Appreciate that.

Cheers,
/z

**Comment by nmstoker** [comment]
Thanks for the kind words @zenny 
As it's not really about this repo, how about I respond on a new thread https://discourse.mozilla.org/c/deep-speech ? I'll follow up on it later in the week and post the link back here when I've done it.

**Comment by zenny** [comment]
@nmstoker Thanks for your prompt reply. I shall eagerly look forward to your link with details of your implementation.

Actually I posted here in spite of irrelevance to this repo with apology to the repo owner because I could find no way to reach you asynchronously via email! If you share one or send an email to garbytrash#gmail, I shall appreciate your gesture. 

Cheers,
/z

**Comment by nmstoker** [comment]
Sorry @zenny - haven't forgotten, just been delayed and distracted with a few other things :slightly_smiling_face:

**Comment by zenny** [comment]
> Sorry @zenny - haven't forgotten, just been delayed and distracted with a few other things 🙂

So thoughtful of you. Eagerly looking forward to (both an email and a new git repo or gist).

**Comment by nmstoker** [comment]
@zenny - I've put a quick post up on the DeepSpeech Discourse here: https://discourse.mozilla.org/t/simple-demo-using-deepspeech-with-tts/49502 and shared the code in a  repo here: https://github.com/nmstoker/SimpleSpeechLoop

**Comment by zenny** [comment]
> @zenny - I've put a quick post up on the DeepSpeech Discourse here: https://discourse.mozilla.org/t/simple-demo-using-deepspeech-with-tts/49502 and shared the code in a repo here: https://github.com/nmstoker/SimpleSpeechLoop

Thanks a zillion. Did I miss your voice model dataset in the repo?

**Comment by nmstoker** [comment]
Yes, I'm sorry - that's a private dataset not for release. However the code is entirely useable with models built on publicly available data (eg LJSpeech and others) or you can use your own dataset if you record one.

For any future discussion, please use the forum link.
