### ISSUE TITLE
How to change the compensation in the process of lpc_from_cepstrum when I want use 80 dimension BFCC?

### ISSUE THREAD

**Issue by lmingde** [mozilla/LPCNet#70]
I want change the BFCC from 18 to 80 , but I don't know how to  change the compensation in process of `lpc_form_cepstrum`

code in `freq.c` line 231-241:
```c
float lpc_from_cepstrum(float *lpc, const float *cepstrum)
{
   int i;
   float Ex[NB_BANDS];
   float tmp[NB_BANDS];
   RNN_COPY(tmp, cepstrum, NB_BANDS);
   tmp[0] += 4;
   idct(Ex, tmp);
   for (i=0;i<NB_BANDS;i++) Ex[i] = pow(10.f, Ex[i])*compensation[i];
   return lpc_from_bands(lpc, Ex);
}
```

**Comment by Liujingxiu23** [comment]
Have you find any solution?

**Comment by Sinnerboy89** [comment]
Any update on this?

**Comment by xiaoyangnihao** [comment]
Same question, any update?

**Comment by jmvalin** [comment]
The compensation is basically just to compensate for higher bands being wider since we want to use the average power in a band as opposed to the sum of all bins in that band.

**Comment by ROAD2018** [comment]
> The compensation is basically just to compensate for higher bands being wider since we want to use the average power in a band as opposed to the sum of all bins in that band.

so, how to compute this 'compensation' ?
