### ISSUE TITLE
"automake failed with exit status:1" ERROR 

### ISSUE THREAD

**Issue by byuns9334** [mozilla/LPCNet#73]
Hi, when I run autogen.sh, I get this error while doing 'autoreconf -isf' .

main::scan_file() called too early to check prototype at /usr/local/bin/aclocal line 618.
Useless use of /d modifier in transliteration operator at /usr/local/share/automake-1.11/Automake/Wrap.pm line 58.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/local/bin/automake line 4113.
Makefile.am:9: Libtool library used but `LIBTOOL' is undefined
Makefile.am:9:   The usual way to define `LIBTOOL' is to add `AC_PROG_LIBTOOL'
Makefile.am:9:   to `configure.ac' and run `aclocal' and `autoconf' again.
Makefile.am:9:   If `AC_PROG_LIBTOOL' is in `configure.ac', make sure
Makefile.am:9:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1

Could you let me know why this happens? Thanks in advance!

**Comment by gmyofustc** [comment]
the same error, waiting for response

**Comment by byuns9334** [comment]
@gmyofustc just 'libtoolize' command solved the problem. hope it works for you too !

**Comment by gmyofustc** [comment]
@byuns9334  Yeah, I works, thanks
