### ISSUE TITLE
How to get source code version of 'dump_data'?

### ISSUE THREAD

**Issue by byuns9334** [mozilla/LPCNet#75]
As 'dump_data' code is in binary, I can't try to use different types of feature or BFCC with different dimensions or whatever... 

Could you please let me know how to do the same thing with './dump_data' ? thanks!

**Comment by zyqdragon** [comment]
I think the dump_data.c in the src folder is the c code of dump_data in binary, so you can do the same thing with './dump_data' by the  dump_data.c
