### ISSUE TITLE
How can I utilize CPU/C only to generate wav(or s16) from f32 ?

### ISSUE THREAD

**Issue by byuns9334** [mozilla/LPCNet#77]
lpcnet_demo generates wav only from bin, and ./src/test_lpcnet.py uses python/GPU. Is there any way to do the same only with CPU/C?

Thanks!

**Comment by alokprasad** [comment]
@byuns9334 LPCNEt is completely implemented in C also , only Training part is keras/Python.

**Comment by mcmar** [comment]
@byuns9334 You have to look at the code because it's not documented in the README, but `lpcnet_demo` also has `-features` and `-synthesis` for creating and consuming `.f32` files https://github.com/mozilla/LPCNet/blob/master/src/lpcnet_demo.c#L49

**Comment by wangshiyao-1119** [comment]
@byuns9334 Hello, I would like to ask, how to generate the "lpcnet_demo" executable file, when I am running "make lpcnet_demo" ,there is an error.

**Comment by arthw** [comment]
@wangshiyao-1119 
```
./autogen.sh
./configure
make
```
Then you will see lpcnet_demo.
