### ISSUE TITLE
Add OpenMP support

### ISSUE THREAD

**Issue by SashaMN** [mozilla/LPCNet#8]
Hi!
I'm trying to increase the speed of LPCNet with OpenMP (and want to make PR after). I ran the profiler, and it says 72% of the time was spent in `sparse_sgemv_accum16` function. So I decided to parallelize that function first. But unfortunately, my code isn't working properly. Do you have any ideas what's wrong with the code below?
```int i, j;
   const int *precomputed_idx[rows];
   const float *precomputed_weights[rows];
   for (i=0;i<rows;i+=16)
   {
      precomputed_weights[i] = weights;
      weights += 16 * (*idx);
      precomputed_idx[i] = idx++;
      idx += *precomputed_idx[i];
   }
   float test_out[4][2000];
   #pragma omp parallel num_threads(2)
   {
      int thread_id;
      const int *local_idx;
      float * restrict y;
      __m256 vy0, vy8;
      int cols;
      const float *local_weights;
      thread_id = omp_get_thread_num();
      #pragma omp for schedule(static)
      for (i=0;i<rows;i+=16)
      {  
         local_weights = precomputed_weights[i];
         y = &out[i];
         vy0 = _mm256_loadu_ps(&y[0]);
         vy8 = _mm256_loadu_ps(&y[8]);
         local_idx = precomputed_idx[i];
         cols = *local_idx++;
         for (j=0;j<cols;j++)
         {
            int id;
            __m256 vxj;
            __m256 vw;
            id = *local_idx++;
            vxj = _mm256_broadcast_ss(&x[id]);

            vw = _mm256_loadu_ps(&local_weights[0]);
            vy0 = _mm256_fmadd_ps(vw, vxj, vy0);

            vw = _mm256_loadu_ps(&local_weights[8]);
            vy8 = _mm256_fmadd_ps(vw, vxj, vy8);
            local_weights += 16;
         }
         _mm256_storeu_ps(&test_out[thread_id][i], vy0);
         _mm256_storeu_ps(&test_out[thread_id][i + 8], vy8);
      }
   }
```
I've got segmenation fault at line `vxj = _mm256_broadcast_ss(&x[id]);` because of defenitely incorrect id value. It always works without errors when I set the number of threads to 1.

**Comment by jmvalin** [comment]
Any particular reason you want OpenMP support? The current code is already much faster than real-time on x86 and faster ARM chips (e.g. smartphones, but not RPi yet).

**Comment by gosha20777** [comment]
Yes, we know. But it loads only 1 thread of cpu. And we are trying to parallel it with open mp. But our code is not works and ve have no idea why? We are wont to understand this promlem and overcome it. That's why we ask you about it.

This fact causes us more bewilderment. And we want to solve this problem. Though, just for fun. And in addition to further increase productivity. I think it does not hurt.

**Comment by gosha20777** [comment]
i ve parallel it...
you can use this code for OpenMP
```cpp
static void sparse_sgemv_accum16(float *out, const float *weights, int rows, const int *idx, const float *x)
{
    int i=-16;
    #pragma omp parallel
    while (i<rows)
    { 
      float * restrict y;
      int cols;
      int j;
      const float *lc_weights;
      _Bool flag=1;
      __m256 vy0, vy8;
      #pragma omp critical
      {
         // initialization
         i+=16;
         if (i>=rows)
            flag=0;
         else 
         {
            y = &out[i];
            cols = *idx++;
            idx+=cols;
            lc_weights=weights;
            weights+=16*cols;
         }
      }
      if (flag) 
      {
         vy0 = _mm256_loadu_ps(&y[0]);
         vy8 = _mm256_loadu_ps(&y[8]);
         for (j=0;j<cols;j++)
         {
            int id;
            __m256 vxj;
            __m256 vw;
            id = cols+j;
            vxj = _mm256_broadcast_ss(&x[id]);

            vw = _mm256_loadu_ps(&lc_weights[0]);
            vy0 = _mm256_fmadd_ps(vw, vxj, vy0);

            vw = _mm256_loadu_ps(&lc_weights[8]);
            vy8 = _mm256_fmadd_ps(vw, vxj, vy8);
            lc_weights += 16;
         }
         _mm256_storeu_ps (&y[0], vy0);
         _mm256_storeu_ps (&y[8], vy8);
      }
   }
}
```

**Comment by jmvalin** [comment]
I'm not sure I understand this code, but I don't see how you can parallelize it without restructuring the data. As for my original question, parallelizing is a means to get the code to run fast enough, but the current code is already fast enough.

**Comment by gosha20777** [comment]
Yes i understand. But it interesting for me)
So now code is fully works. And lpcnet uses all cpu cores.

But in fact code is not become much faster (even a bis slower in little samples) and i have no idea why? When i looked through profiles sparse_sgemv_accum16 takes 80% of time that's while i ve decided to parallel it. but performance even NOT faster 2 times... Can someone explain why it so?

```cpp
static void sparse_sgemv_accum16(float *out, const float *weights, int rows, const int *idx, const float *x)
{  
   int i, j;
   //initialization
   const int *precomputed_idx[rows];
   const float *precomputed_weights[rows];
   for (i=0;i<rows;i+=16)
   {
      precomputed_weights[i] = weights;
      weights += 16 * (*idx);
      precomputed_idx[i] = idx++;
      idx += *precomputed_idx[i];
   }

   #pragma omp parallel
   {
      const int *lc_idx;
      const float *lc_weights;
      float * restrict y;
      __m256 vy0, vy8;
      int cols;
      for (i=0;i<rows;i+=16)
      {  
         lc_weights = precomputed_weights[i];
         y = &out[i];
         vy0 = _mm256_loadu_ps(&y[0]);
         vy8 = _mm256_loadu_ps(&y[8]);
         lc_idx = precomputed_idx[i];
         cols = *local_idx++;
         #pragma omp critical
         for (j=0;j<cols;j++)
         {
            int id;
            __m256 vxj;
            __m256 vw;
            id = *lc_idx++;
            vxj = _mm256_broadcast_ss(&x[id]);

            vw = _mm256_loadu_ps(&lc_weights[0]);
            vy0 = _mm256_fmadd_ps(vw, vxj, vy0);

            vw = _mm256_loadu_ps(&lc_weights[8]);
            vy8 = _mm256_fmadd_ps(vw, vxj, vy8);
            lc_weights += 16;
         }
         _mm256_storeu_ps (&y[0], vy0);
         _mm256_storeu_ps (&y[8], vy8);
      }
   }
}
```

**Comment by gosha20777** [comment]
I ve parallelized main loop in functions from main and divided input data. It worked and I got a slight increase in performance but in those places where the data were divided, the bangs and noise could be heard. Therefore, this requires more complex work and not the fact that the performance gain will be good.

We can close this issue.

**Comment by hdmjdp** [comment]
@jmvalin @gosha20777  faster ARM chips? which one, what is the  main frequency? thank you.
> Any particular reason you want OpenMP support? The current code is already much faster than real-time on x86 and faster ARM chips (e.g. smartphones, but not RPi yet).
