### ISSUE TITLE
Cannot import name 'activations' using keras 2.3.1

### ISSUE THREAD

**Issue by nscotto** [mozilla/LPCNet#81]
Hi, I can't load the model because of a compatibility version with keras 2.3.1:
```ImportError: cannot import name 'activations' ```
(from `keras.layers`) in *mdense.py* line 3.
Some imports have moved from `keras.layers` to `keras`

**Comment by meowtech** [comment]
@nscotto 
try this change:
```
from tensorflow.keras.layers import InputSpec
from keras import activations, initializers, regularizers, constraints
```

**Comment by olferuk** [comment]
I've tried @meowtech advice and it actually helps.

**Comment by nscotto** [comment]
Thanks for the answer. 
I was just signalling for better support. ;)

**Comment by Kanhaiya54** [comment]
Thanks for the help, it actually worked!
