### ISSUE TITLE
Tacotron2+LPCNet problem

### ISSUE THREAD

**Issue by Jwei-Lee** [mozilla/LPCNet#83]
I train LPCNet with feature generated by './dump_data -train input.s16 features.f32 data.u8'， i think it is 55dim feature. and, i get a right LPCNet model, it can generate normal voice from a test.f32 file.
then, i did the flollowing:
1. i change the test.f32  file to 20dim feature new.f32 using the following code(55d to 20d)
2. then change the new.f32 to 55dim new_test.f32 using the following code(convert 20d to 55d when test)
3. then using the LPCNet model i got above to generate wav with new_test.f32, but the wav is all noise

Is there anyone know, what's wrong?

![image](https://user-images.githubusercontent.com/56538895/67273907-f8cd2380-f4f1-11e9-9548-143cbfaec168.png)

**Comment by ZhaoZeqing** [comment]
Could you share your wav with noise?

I had tried to remove this line https://github.com/mozilla/LPCNet/blob/master/src/dump_data.c#L96
then worked.

But I had also tried the raw code, the noise is unstable.
Maybe it need more experiments.
