### ISSUE TITLE
How to transform the "test.s16" file into pcm files?

### ISSUE THREAD

**Issue by zyqdragon** [mozilla/LPCNet#87]
the "test.s16" is generated by the "./src/test_lpcnet.py test_features.f32 test.s16" script. Could the "test.s16" be transformed into pcm files?

**Comment by xDuck** [comment]
You can use ffmpeg to convert it to a wav file. The .s16 file is already PCM data.

`ffmpeg -f s16le -ar 16k -ac 1 -i test.s16 test.wav`
