### ISSUE TITLE
About loss and sparse_categorical_accuracy

### ISSUE THREAD

**Issue by azraelkuan** [mozilla/LPCNet#9]
Hi, I use this repo to train my own dataset, but i found that the sparse_categorical_accuracy increase very slowly
![image](https://user-images.githubusercontent.com/23380152/49642140-28e01500-fa4d-11e8-94a5-3f6d53a1d1fc.png)

how about your training process?

**Comment by azraelkuan** [comment]
my step:
1. find wav_dir -iname \*.wav | sort -R | tr "\n" " " | xargs -d " " -I{} sox {} -r 16000 -b 16 -c 1 -e signed-integer -t raw - > input.s16
2. ./dump_data input.s16 features.f32 pcm.s16
3. python train_lpcnet.py

**Comment by azraelkuan** [comment]
thanks for your work, in my experience, when the loss is around 2, the generate wav is very good.
this is the spectrum of the generated wav
![image](https://user-images.githubusercontent.com/23380152/49682368-e28ec280-faed-11e8-94d2-1a18003e3538.png)

**Comment by HallidayReadyOne** [comment]
Hi, @azraelkuan, the audio mentioned above is generated using features extracted from the original audio or predicted features?
