### ISSUE TITLE
impulse noise issue

### ISSUE THREAD

**Issue by weixsong** [mozilla/LPCNet#94]
Hi, does anyone meet the impulse noise issue?

Is there a post-processing method that could remove the impulse noise?

**Comment by jarred1989** [comment]
@weixsong hi, I encountered the same issue, I'm not sure whether it has something to do with cutting off head and tail silence of wav.  Have you solved this problem? How?

**Comment by zhangjh915** [comment]
Same thing here. I have impulse noise only at the beginning of a synthesized wave from predicted lpc features. With the same input, some models produce little impulse but others produce huge ones. No patterns have been found so I suggest it is related to the robustness of the model.
I have also tried to keep the silence, but it did not help. Anyone get the solution?
