### ISSUE TITLE
 how to get pretty good result using small amount of data

### ISSUE THREAD

**Issue by BridgetteSong** [mozilla/LPCNet#98]
such as 1h or less?

**Comment by gosha20777** [comment]
Just 
1. take Tacotron2 and wawe net vocoder. There are many good pretrained models in the Web. (for ch / ch / fr / de / ru /even ko) 
2. Take some text strings
3. Generate sounds.
4. Profit!

**Comment by BridgetteSong** [comment]
training from a pretrained model can get a pretty good result.
